- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - check-requirements
      - publish-openstack-sphinx-docs
    check:
      jobs:
        - openstack-tox-cover:
            voting: false

